### ISSUE TITLE
Undefined Method

### ISSUE THREAD

**Issue by ad3n** [go-gorm/sqlserver#17]
![Screenshot from 2021-02-16 15-56-22](https://user-images.githubusercontent.com/7464920/108040290-b4af4c00-706f-11eb-803e-a9f468b791a5.png)

When using SQLServer Driver, i got this error

**Comment by ad3n** [comment]
![Screenshot from 2021-02-16 15-59-23](https://user-images.githubusercontent.com/7464920/108040532-ffc95f00-706f-11eb-8bb9-3df0ed74aad8.png)

This is my config

**Comment by vimiix** [comment]
Hi @jinzhu , I got same error.

**Comment by jinzhu** [comment]
update GORM to latest version.

**Comment by 5idu** [comment]
`v1.0.6` still have the problem~~~
