### ISSUE TITLE
uuid wrong data problem

### ISSUE THREAD

**Issue by bakbuz** [go-gorm/sqlserver#19]
I am using a uuid package (RFC 4122) and I am receiving a wrong data

```
newUser := &User{
	Email:    "a@a.com",
	UniqueID: uuid.New(),
	JoinedAt: time.Now(),
}
_ = db.Create(&newUser).Error
fmt.Println(newUser.UniqueID.String(), "Inserted Data")
```
**521a8bc1-2641-4e6f-9a82-e8e6b15da603 Inserted Data** (and database record)

```
user, _ := db.Where(&User{Email: "a@a.com"}).First(&user).Error
fmt.Println(user.UniqueID.String(), "Query Result")
```
**c18b1a52-4126-6f4e-9a82-e8e6b15da603 Query Result**

First blocks are looking incorrect.

Best regards

packages
github.com/google/uuid v1.2.0
gorm.io/driver/sqlserver v1.0.6
gorm.io/gorm v1.21.2

**Comment by jinzhu** [comment]
Hi, can you create a playground PR to reproduce the issue, and put it to gitHub.com/go-gorm/gorm

**Comment by xiongdashan** [comment]
How is this problem solved?

**Comment by deepak-z** [comment]
How is this problem solved?
