### ISSUE TITLE
在哪里填写数据库password？

### ISSUE THREAD

**Issue by zhuqiyun** [go-gorm/sqlserver#2]

**Comment by zhuqiyun** [comment]
> ## Your Question
> ## The document you expected this should be explained
> ## Expected answer

	dsn := "sqlserver://gorm:sa@192.168.0.201:1433?pwd=XINGshan123,database=wms_server_v1"
	_, err := gorm.Open(sqlserver.Open(dsn), &gorm.Config{})

   这样子连接失败

**Comment by jinzhu** [comment]
https://github.com/denisenkom/go-mssqldb#connection-parameters-and-dsn
