### ISSUE TITLE
sqlserver 密码中包含@符号不能连接数据库

### ISSUE THREAD

**Issue by xiaogu-space** [go-gorm/sqlserver#25]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description

sqlserver 密码中包含@符号不能连接数据库

**Comment by DeivaLiang** [comment]
In my case, the password having @, then it will promote an error like this:
failed to initialize database, got error Login error: read tcp 10.0.1.12:34916->10.0.1.6:1555: read: connection reset by peer
panic: Login error: read tcp 10.0.1.12:34916->10.0.1.6:1555: read: connection reset by peer

**Comment by jinzhu** [comment]
Should open an issue in https://github.com/denisenkom/go-mssqldb

**Comment by cute-angelia** [comment]
https://github.com/denisenkom/go-mssqldb/issues/651

```
dsn = fmt.Sprintf("sqlserver://%s:%s@%s:%d?database=%s", cfg.Username, strings.ReplaceAll(url.QueryEscape(cfg.Password), "+", "%20"), cfg.Host, cfg.Port, cfg.Database)

```
