### ISSUE TITLE
clause.OnConflict is silently ignored

### ISSUE THREAD

**Issue by selaux** [go-gorm/sqlserver#47]
## Reproduction Link

Unfortunately I cannot provide a playground link as I am on an ARM system, but here is a link to a reproduction repo.

https://github.com/selaux/gorm-sql-server-upsert-issue

## Description

If I use the following code with SQL Server I expect the selected row to be updated when I call this code a second time (this is a short excerpt of the code, for the full code see the example repo above).

```golang
type TestModel struct {
	gorm.Model
	Matcher string `gorm:"uniqueIndex;size:512"`
	Data    string
}

result := db.Clauses(clause.OnConflict{
	Columns:   []clause.Column{{Name: "matcher"}},
	DoUpdates: clause.Assignments(map[string]interface{}{"age": 55}),
}).Create(&User{
	Name: "foobar",
	Age:  30,
})
```

Instead the following error is thown: `mssql: Cannot insert duplicate key row in object 'dbo.test_models' with unique index 'idx_test_models_matcher'. The duplicate key value is (foobar).`

I am aware that SQL Server does not support the `ON CONFLICT` clause directly, but there are existing solutions to work around this, e.g. [here](https://sqlperformance.com/2020/09/locking/upsert-anti-pattern) or [here](https://michaeljswart.com/2017/07/sql-server-upsert-patterns-and-antipatterns/). It would be nice for GORM to either:

- Map the `clause.OnConflict` clause to one of those implementations
- Return an error that explicitly states that `clause.OnConflict` is not supported for SQL Server and add this information to GORMs documentation

**Comment by jinzhu** [comment]
We should support this with `merge into` now.

**Comment by stevefoxuser** [comment]
问题仍然存在。。一样的代码，一样的报错 包的版本 	gorm.io/driver/sqlserver v1.5.3 // indirect
	gorm.io/gorm v1.25.12 // indirect
